Repository ifupdown-ng/ifupdown-ng, pull requests merged in 2020-10, with the labels that each got.

#90 Clean up link executor
  executor-scripts/linux/link
Labels: enhancement

#88 Add files required for Debian packaging
  dist/debian/ifupdown-ng.networking.service
  dist/debian/networking
  dist/debian/networking.default
Labels: enhancement

#89 Add support for VXLAN interface
  doc/interfaces-vxlan.scd
  doc/interfaces.scd
  executor-scripts/linux/vxlan
  libifupdown/interface-file.c
  tests/linux/Kyuafile
  tests/linux/vxlan_test
Labels: documentation, enhancement

#99 Add support for bonding / LAGs.
  Makefile
  doc/interfaces-bond.scd
  doc/interfaces.scd
  executor-scripts/linux/bond
  libifupdown/interface-file.c
  libifupdown/lifecycle.c
Labels: enhancement

#87 Add support for veth interface pairs
  doc/interfaces.scd
  executor-scripts/linux/link
Labels: enhancement

#98 static executor: Add support for IPv4 'pointopoint' addresses.
  doc/interfaces.scd
  executor-scripts/linux/static
  libifupdown/interface-file.c
  tests/fixtures/static-eth0-ptp.interfaces
  tests/linux/static_test
Labels: enhancement

#92 Man pages for B.A.T.M.A.N. adv., bridges, ethtool, VRFs
  Makefile
  doc/interfaces-batman.scd
  doc/interfaces-bridge.scd
  doc/interfaces-ppp.scd
  doc/interfaces-vrf.scd
  doc/interfaces-wireguard.scd
  doc/interfaces.scd
Labels: documentation

#100 Expose all adresses and gateways as environment variables
  executor-scripts/linux/static
  libifupdown/lifecycle.c
  libifupdown/version.c
  tests/linux/static_test
Labels: enhancement

#101 Generalize B.A.T.M.A.N. .adv. option handling
  executor-scripts/linux/batman
Labels: enhancement

#102 docs: Fix format of VXLAN examples
  doc/interfaces-vxlan.scd
Labels: documentation

#104 bond executor: grep for options only once
  executor-scripts/linux/bond
Labels: enhancement

#106 Update build documentation as well as admin guide
  README.md
  dist/ifupdown-ng.conf.example
  doc/ADMIN-GUIDE.md
Labels: documentation

#107 Always convert netmasks to CIDR when configuring interfaces
  cmd/ifquery.c
  libifupdown/dict.c
  libifupdown/dict.h
  libifupdown/interface.c
  libifupdown/interface.h
  libifupdown/lifecycle.c
Labels: bug

#114 Introduce compatibility layer framework
  Makefile
  cmd/ifupdown.c
  libifupdown/compat.c
  libifupdown/compat.h
  libifupdown/libifupdown.h
Labels: enhancement

#111 vlan aware bridging
  Makefile
  cmd/ifquery.c
  dist/ifupdown-ng.conf.example
  doc/ADMIN-GUIDE.md
  doc/ifdown.scd
  doc/ifup.scd
  doc/ifupdown-ng.conf.scd
  doc/interfaces-bridge.scd
  doc/interfaces.scd
  executor-scripts/linux/bridge
  libifupdown/compat.c
  libifupdown/config-file.c
  libifupdown/config-file.h
  libifupdown/interface-file.c
Labels: documentation, enhancement

#120 docs: document ifstate
  Makefile
  doc/ifstate.scd
  doc/interfaces.scd
Labels: documentation
